// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.gabrielspassos.poc.proto.user;

public interface DeleteUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.DeleteUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
