// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.gabrielspassos.poc.proto.user;

public interface ListUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.ListUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.user.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.user.User user = 1;</code>
   * @return The user.
   */
  com.gabrielspassos.poc.proto.user.User getUser();
  /**
   * <code>.user.User user = 1;</code>
   */
  com.gabrielspassos.poc.proto.user.UserOrBuilder getUserOrBuilder();
}
