// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.gabrielspassos.poc.proto.user;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_CreateUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_DeleteUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_DeleteUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_DeleteUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_DeleteUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_ListUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_ListUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_ListUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_ListUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\"/\n\004User\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"-\n\021CreateUse" +
      "rRequest\022\030\n\004user\030\001 \001(\0132\n.user.User\".\n\022Cr" +
      "eateUserResponse\022\030\n\004user\030\001 \001(\0132\n.user.Us" +
      "er\"#\n\021DeleteUserRequest\022\016\n\006userId\030\001 \001(\t\"" +
      "$\n\022DeleteUserResponse\022\016\n\006userId\030\001 \001(\t\"\021\n" +
      "\017ListUserRequest\",\n\020ListUserResponse\022\030\n\004" +
      "user\030\001 \001(\0132\n.user.User2\322\001\n\013UserService\022A" +
      "\n\nCreateUser\022\027.user.CreateUserRequest\032\030." +
      "user.CreateUserResponse\"\000\022A\n\nDeleteUser\022" +
      "\027.user.DeleteUserRequest\032\030.user.DeleteUs" +
      "erResponse\"\000\022=\n\010ListUser\022\025.user.ListUser" +
      "Request\032\026.user.ListUserResponse\"\0000\001B%\n!c" +
      "om.gabrielspassos.poc.proto.userP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
    internal_static_user_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_CreateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_user_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_CreateUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_user_DeleteUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_DeleteUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_DeleteUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_DeleteUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_user_DeleteUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_DeleteUserResponse_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_ListUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_user_ListUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_ListUserRequest_descriptor,
        new java.lang.String[] { });
    internal_static_user_ListUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_user_ListUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_ListUserResponse_descriptor,
        new java.lang.String[] { "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
